### ISSUE TITLE
Apply Cardstack styleguide

### ISSUE THREAD

**Issue by jenweber** [cardstack/guidemaker-cardstack-template#2]
From Chris Gardella:

Look at whitepaper for inspiration
https://cardstack.com/whitepaper/architecture/different-levels-of-decentralization

-------------------------
Landing page (from Cardstack.com)

Headers (all caps)
Karbon Regular - style normal, weight 700, size 28px, line height 39px, color #000000

Body copy
Karbon Regular - style normal, weight 400, size 24px, line height 34px, color #4a4a4a

-------------------------
Internal pages (from Cardstack.com)

Headers
Karbon  - style normal, weight 700, size 23px, line height 38px, color #4a4a4a

Body copy (white papers)
SourceSerifPro - style normal, weight 400, size 20px, line height 34px, color #4a4a4a

OR

Body copy (bios)
Karbon - style normal, weight 400, size 23px, line height 34px, color #4a4a4a

-------------------------
Personal Preference

Page Title
Karbon  - style normal, weight 400, size 44px, line height 65px, color #6638ff

Headers (body)
Karbon - style normal, weight 700, size 23px, line height 38px, color #000000

Body copy (bios)
Karbon - style normal, weight 400, size 20px, line height 32px, color #4a4a4a

For your left nav I'd use the current sizes and replace font with Karbon semi bold for section headers and Karbon regular for sub sections.  On the online whitepaper we've been using a neon purple #6638ff to denote active section and active sub section.

For links we've been using the same neon purple #6638ff, no underline.  Underline on hover.

**Comment by jenweber** [comment]
- [ ] new "neon purple" var #6638ff,
- [ ] navbar Page Title - does `#6638ff` background pass a11y contrast? 
- [x] title logo is an image, so no eights applied
- [ ] Headers style normal, weight 700, size 23px, line height 38px, color #000000
- [ ] body style normal, weight 400, size 20px, line height 32px, color #4a4a4a
    - [ ] alt SourceSerifPro - style normal, weight 400, size 20px, line height 34px, color #4a4a4a
- [ ] TOC semi-bold for section headers, regular for subsections
- [ ] li - neon purple, no outline. Ok for a11y?

**Comment by jenweber** [comment]
Need to change headers for pages and in the sidebar to "Karbon" font weight 500
